---
Name: iqprotectedareapage
---
Page:
  extensions:
    - IQnection\ProtectedArea\Page\Page
PageController:
  extensions:
    - IQnection\ProtectedArea\Page\PageController
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iqnection-pages/protectedareapage:css/cms/leftandmainadditions.css
---