---
Name: iqprotectedareapage
---
Page:
  extensions:
    - ProtectedAreaPageExtension
PageController:
  extensions:
    - ProtectedAreaPageControllerExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - iq-protectedareapage/cms/css/leftandmainadditions.css
---